{
  'data_paths': {
    'import_folder': 'raw_data',
    'export_folder': 'clean_data',
    'dict_file': 'dict/merged_dictionary.csv',
    'db_file': 'data_base/db_example.db'
  },
  'data_file_settings': {
    'extension': 'gz', # data files'  extension
    'index_column': 'adId',
    'date_column': 'researchDate' #'researchDate' researchMonth
  },
  'dict_file_settings': {
    'extension': 'gz',
    'add_separator': ', ',
    'col_indexes': { # columns' indexes in the mapping dictionary containing settings
      'action': 0,  # update or delete setting
      'match': 1,
      'search': 2,
      'term': 4  # search string used after match setting in the SQL query
    },
  },

  'database_settings': {
    'table_name': 'data_table'
  },
  'read_settings': { # general settings for pandas CSV reader
    "from_csv": {
      "separator": ";",
      "encoding": "utf8",
      "decimal_comma": True,
      "skip_rows": 0,
      "has_header": True,
      "ignore_errors": True,
      "rechunk": False
    }
  },
  'export_settings': {
    "to_csv": {
      "chunk_size": 10000,
      "separator": ";",
      "decimal_comma": True,
      "encoding": "utf8",
      "include_header": True,
      "compression": "gzip"
    }
  },
}